version: "3.7"

services:
  db:
    container_name: bakalarka-db
    image: mariadb:10.4.8
    volumes:
      - db_data:/var/lib/mysql
      - .:/home
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
    container_name: bakalarka-adminer
    image: adminer:4.7.4
    depends_on:
      - db
    ports:
      - 8081:8080

  php:
    container_name: bakalarka-php
    build: ./docker
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCUMENT_ROOT-.}:/var/www/html:delegated
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./docker/logs/apache2}:/var/log/apache2

volumes:
  db_data: {}
